@startuml Schéma global de l'application interne DigiCheese
left to right direction
skinparam linetype ortho

'actor Client
actor "Opérateur colis"
actor "Opérateur stock" 
actor "Administrateur" 

package "Application interne DigiCheese"  {

    package "Colis" {
        rectangle "Gestion des commandes" {
            
        }
        'rectangle Suvie des commandes {}
    }

    package "Stock" {
        rectangle "Gestion des stock d'objets" {

        }
        rectangle "Gestion des stock d'emballages" {

        }
    }

    package "Administration" {
        rectangle "Gestion des objets" {

        }
        rectangle "Gestion des frais de ports" {

        }
        rectangle "Gestion des comptes clients" {

        }
        rectangle "Produtcion de statistiques" {

        }
        rectangle "Gestion des embllages" {

        }
    }

    
}

'Client -- Gestion Compte Client
"Administrateur" -- "Administration"
"Opérateur colis" -- "Colis"
"Opérateur stock" -- "Stock"

"Colis" <--> "Stock"
"Administration" <--> "Stock"
"Administration" <--> "Colis"

title Schéma global de l'application interne Digicheese

@enduml