@startuml Diagramme de séquence de la création d'une commande

actor "Opérateur colis"

participant "Application interne DigiCheese"

ref over "Opérateur colis", "Application interne DigiCheese", CompteClient : le client doit etre trouver avant et la commande ne peut être fait que depuis le client

"Opérateur colis" -> "Application interne DigiCheese" : CréerCommande()
activate "Application interne DigiCheese"

"Application interne DigiCheese" -> Commande : IntialiserCommande(idClient)
activate Commande 

'Commande -> Client : DemandeID()
'Client --> Commande : RetourneID

'Commande -> "Application interne DigiCheese" : DemanderDonner()
'"Application interne DigiCheese" -> "Opérateur colis" : RentrerInformationCommande()

"Opérateur colis" -> "Application interne DigiCheese" : ChoixDesProduit(nomObjet, nbObjets)
"Application interne DigiCheese" -> "Application interne DigiCheese" : RechercherListesDObjet(nomObjet)
"Application interne DigiCheese" --> "Application interne DigiCheese" : Retourne une ListeDObjets
"Application interne DigiCheese" -> "Application interne DigiCheese" : RechercherObjetDisponible(ListeDObjets, nbObjets)
"Application interne DigiCheese" --> "Application interne DigiCheese" : Liste ou juste l'id d'un objet
"Application interne DigiCheese" -> Commande : AjouterObjets(Liste ou idObjet)

"Application interne DigiCheese" -> Commande : AjouterPrix(prixObjets * nbObjets)
Commande --> "Application interne DigiCheese" : Prix mis à jour

"Application interne DigiCheese" -> Objet : ChangementDeDisponiblite(Rendre indisponible)
activate Objet

Objet --> "Application interne DigiCheese" : Le changement de status a été fait

ref over "Opérateur colis", "Application interne DigiCheese", Commande, Emballage : Choix de l'emballage a ajouter à la commande

title Diagramme de séquence de la création d'une commande
@enduml