@startuml Diagramme de séquence de l'ajout d'un emballage à une commande

actor "Opérateur colis"

'"Opérateur colis" -> "Application interne DigiCheese" : GérerCommande(idCommande)
'activate "Application interne DigiCheese"
'"Application interne DigiCheese" -> "Application interne DigiCheese" : ChercherCommande(idCommande)
'"Application interne DigiCheese" --> "Application interne DigiCheese" : Commande trouvé
'"Application interne DigiCheese" --> "Opérateur colis" : Affiché la commande
ref over "Opérateur colis", "Application interne DigiCheese": Gestion d'une commande
activate "Application interne DigiCheese"

"Opérateur colis" -> "Application interne DigiCheese" : RechercherUnEmballage(nomObjets, nombreObjets)
"Application interne DigiCheese" -> "Application interne DigiCheese" : RechercherTypeEmballageDisponible(nomObjets, nombreObjets)
"Application interne DigiCheese" --> "Application interne DigiCheese" : Liste d'emballage correspondant

"Application interne DigiCheese" --> "Opérateur colis" : Affichage de la liste des emballages

"Opérateur colis" -> "Application interne DigiCheese" : ChoissirEmballage(idEmballage)
"Application interne DigiCheese" -> Emballage : ModificationDuStatus(idEmballage, Indisponible)
activate Emballage
Emballage --> "Application interne DigiCheese" : Status modifier
deactivate Emballage

"Application interne DigiCheese" -> Commande : AjouterEmballage(idEmballage)
activate Commande
Commande --> "Application interne DigiCheese" : L'emballage à bien été ajouté

"Application interne DigiCheese" -> Commande : MiseAJourPoids(poidsEmballage)
Commande --> "Application interne DigiCheese" : Poids mis à jour

"Application interne DigiCheese" -> Commande : MiseAJourPrix(prixEmballage)
Commande --> "Application interne DigiCheese" : Prix mis à jour
deactivate Commande

title Diagramme de séquence de la gestion d'une commande lors de l'ajout d'emballage
@enduml