@startuml Diagramme de séquence de la création d'un compte client

actor "Opérateur colis"

'"Opérateur colis" -> "Application interne DigiCheese" : RechercherUnClient(nom,prenom)
'activate "Application interne DigiCheese"
'"Application interne DigiCheese" -> "Application interne DigiCheese" : ChercherCompteClient(nom,prenom)
'"Application interne DigiCheese" --> "Application interne DigiCheese" : Compte client non trouver
'"Application interne DigiCheese" --> "Opérateur colis" : Client non trouver

ref over "Opérateur colis", "Application interne DigiCheese" : GestionCompteClient
activate "Application interne DigiCheese"

"Opérateur colis" -> "Application interne DigiCheese" : CreerUnCompteClient(nom, prenom, ...)
"Application interne DigiCheese" ->  CompteClient : IntialiserUnNouveauxCompte(nom, prenom, ...)
activate CompteClient

'"Opérateur colis" -> "Application interne DigiCheese" : AjouterAdresse(ville, codepostal, adresse)
CompteClient -> AdressePostal : NouvelleAdresse(idClient, ville, codepostal, adresse)
activate AdressePostal
AdressePostal --> CompteClient : Adresse crée

"Opérateur colis" -> "Application interne DigiCheese" : AjouterUnSolde(solde)
"Application interne DigiCheese" -> CompteClient : AjouterPrix(solde)

title Diagramme de séquence de la création d'un compte client
@enduml