@startuml Diagramme de séquence du calcul des frais de ports

actor "Opérateur colis"

'"Opérateur colis" -> "Application interne DigiCheese" : GererCommande(idCommande)
'activate "Application interne DigiCheese"
'"Application interne DigiCheese" -> "Application interne DigiCheese" : ChercherCommande(idCommande)
'"Application interne DigiCheese" --> "Application interne DigiCheese" : Commande trouvé
'"Application interne DigiCheese" --> "Opérateur colis" : Affiche la commande
ref over "Opérateur colis", "Application interne DigiCheese": Gestion d'une commande
activate "Application interne DigiCheese"



"Opérateur colis" -> "Application interne DigiCheese" : AfficherFraisDePorts(idCommande)

"Application interne DigiCheese" -> Commande : AfficherPoids()
activate Commande
Commande --> "Application interne DigiCheese" : Retourne le poids
deactivate Commande

"Application interne DigiCheese" -> "Application interne DigiCheese" : RechercherTimbres(poidsCommande)
"Application interne DigiCheese" --> "Application interne DigiCheese" : Retourne timbre disponible correspondant

"Application interne DigiCheese" -> TarifsPostaux : AfficherPrix(idTimbre)
activate TarifsPostaux
TarifsPostaux --> "Application interne DigiCheese" : Retourne le prix
deactivate TarifsPostaux

"Application interne DigiCheese" -> Commande : AfficherPrix(idCommande)
activate Commande
Commande --> "Application interne DigiCheese" : Retourne le prix
deactivate Commande

"Application interne DigiCheese" -> "Application interne DigiCheese" : CalculFraisDePorts(prixCommande, prixTimbre)
"Application interne DigiCheese" --> "Application interne DigiCheese" : Retourne le résultat du calcul

"Application interne DigiCheese" --> "Opérateur colis" : Affiche les frais de ports et le timbre correspondant

title Diagramme de séquence de la gestion d'une commande lors du calcul des fraits de ports
@enduml