@startuml Diagramme de séquence d'une connexion à l'application interne

actor "Opérateur"

"Opérateur" -> "Application interne DigiCheese" : Connexion(identifiant, motdepasse)
activate "Application interne DigiCheese"
"Application interne DigiCheese" -> "Application interne DigiCheese" : RechercherCompteUtilisateur(identifiant, motdepasse)

alt Identification valide
    "Application interne DigiCheese" --> "Application interne DigiCheese" : Utilisateur valide
    "Application interne DigiCheese" --> "Opérateur" : Connexion autorisé et l'utilisateur est redirigé vers la page d'acceuil
else Identification refuser
    "Application interne DigiCheese" --> "Application interne DigiCheese" : Utilisateur non trouvé
    "Application interne DigiCheese" --> "Opérateur" : Connexion refusé
end
title Diagramme de séquence de la connexion d'un Opérateur sur l'application interne DigiCheese
@enduml