@startuml validation frais de port/conditionnement

actor "Opérateur colis"

'"Opérateur colis" -> "Application interne DigiCheese" : GererCommande(idCommande)
'activate "Application interne DigiCheese"

'"Application interne DigiCheese" -> "Application interne DigiCheese" : ChercherCommande(idCommande)
'"Application interne DigiCheese" --> "Application interne DigiCheese" : Commande trouver
'"Application interne DigiCheese" --> "Opérateur colis" : Affiche la commande
ref over "Opérateur colis", "Application interne DigiCheese": Gestion d'une commande
activate "Application interne DigiCheese"


"Opérateur colis" -> "Application interne DigiCheese" : ValiderFraisDePorts(idCommande)

"Application interne DigiCheese" -> Commande : AfficherPoids()
activate Commande
Commande --> "Application interne DigiCheese" : Retourne le poids
deactivate Commande

"Application interne DigiCheese" --> "Opérateur colis" : Afficher poids commande
"Application interne DigiCheese" -> "Opérateur colis" : ValiderPoidsCommande()
"Opérateur colis" --> "Application interne DigiCheese" : Valide le poids de la commande

"Application interne DigiCheese" -> Commande : AfficherPrix()
activate Commande
Commande --> "Application interne DigiCheese" : Retourne le prix

"Application interne DigiCheese" -> Commande : RechercherClient()
Commande --> "Application interne DigiCheese" : Retourne l'id du client
deactivate Commande

"Application interne DigiCheese" -> CompteClient : AfficherSolde()
activate CompteClient
CompteClient --> "Application interne DigiCheese" : Retourne le solde du client
deactivate CompteClient

"Application interne DigiCheese" -> "Application interne DigiCheese" : ComparaisonPrix(SoldeClient, PrixCommande)
"Application interne DigiCheese" --> "Application interne DigiCheese" : Les prix correspondent
"Application interne DigiCheese" --> "Opérateur colis" : Le solde du client et les frais de la commande correspondent

"Application interne DigiCheese" -> "Opérateur colis" : ValiderCondtionnement()
"Opérateur colis" --> "Application interne DigiCheese" : Valide le condtionnement

"Application interne DigiCheese" -> Commande : ChangementDEtat()
activate Commande
Commande --> "Application interne DigiCheese" : Etat mis à jour
deactivate Commande


title Diagramme de séquence de la validation des frais de ports
@enduml