@startuml Cas d'utilisation gestion des stocks emballage

actor "Opérateur stock"
actor "Administrateur"

package "Application interne DigiCheese" {
    
    'usecase Ajouter_un_nouvel_objet
    'usecase Modifier_les_données_d_un_objet

    usecase "Gérer le stock d'emballages"
    usecase "Gérer le stock de timbre"
    
    usecase "Verifier le nombre d'emballage disponible"
    usecase "Signaler la rupture de stock d'emballage"
    usecase "Comander des emballages"

    usecase "Vérifier le nombre de timbre disponible"
    usecase "Signaler la rupture de stock de timbre"
    usecase "Commander des timbres"

    usecase Consulter_l_emplacement_d_un_type_d_emballages
    usecase Consulter_l_emplacement_d_un_emballages

    usecase Consulter_l_emplacement_d_un_type_de_timbre
    usecase Consulter_l_emplacement_d_un_timbre

    usecase Ajouter_des_lots_d_emballages

    usecase Ajouter_des_lots_de_timbre

}

"Administrateur" -|> "Opérateur stock"

'"Administrateur" -- Ajouter_un_nouvel_objet
'"Administrateur" -- Modifier_les_données_d_un_objet

"Opérateur stock" -- "Gérer le stock d'emballages"
"Gérer le stock d'emballages" <-- "Verifier le nombre d'emballage disponible" : <<extend>>
"Verifier le nombre d'emballage disponible" <-- "Signaler la rupture de stock d'emballage" : <<extend>>
"Verifier le nombre d'emballage disponible" <-- "Comander des emballages" : <<extends>>

"Gérer le stock d'emballages" <-- Consulter_l_emplacement_d_un_type_d_emballages : <<extends>>
Consulter_l_emplacement_d_un_type_d_emballages <-- Consulter_l_emplacement_d_un_emballages : <<extends>>

"Gérer le stock d'emballages" <-- Ajouter_des_lots_d_emballages : <<extends>>

note "Permet de consulter le status des emballages : réserver pour une commande, détruit, disponible..." as N1
N1 .. "Verifier le nombre d'emballage disponible"

note "permettrai de signaler aux personnes a charge de commender les goodies qu'il faut en faire" as N2
N2 .. "Comander des emballages"

note "Ajoute dans la base de données les nouveaux lots d'objets déjà présents dans la base de données" as N3
N3 .. Ajouter_des_lots_d_emballages


"Opérateur stock" -- "Gérer le stock de timbre"
"Gérer le stock de timbre" <-- "Vérifier le nombre de timbre disponible" : <<extend>>
"Vérifier le nombre de timbre disponible" <-- "Signaler la rupture de stock de timbre" : <<extend>>
"Vérifier le nombre de timbre disponible" <-- "Commander des timbres" : <<extends>>

"Gérer le stock de timbre" <-- Consulter_l_emplacement_d_un_type_de_timbre : <<extends>>
Consulter_l_emplacement_d_un_type_de_timbre <-- Consulter_l_emplacement_d_un_timbre : <<extends>>

"Gérer le stock de timbre" <-- Ajouter_des_lots_de_timbre : <<extends>>

note "Permet de consulter le status des emballages : réserver pour une commande, détruit, disponible..." as N4
N4 .. "Vérifier le nombre de timbre disponible"

note "permettrai de signaler aux personnes a charge de commender les goodies qu'il faut en faire" as N5
N5 .. "Commander des timbres"

note "Ajoute dans la base de données les nouveaux lots d'objets déjà présents dans la base de données" as N6
N6 .. Ajouter_des_lots_de_timbre
@enduml