@startuml Gestion administrative d'un objet

actor "Administateur" 

package "Application interne DigiCheese" {
    usecase "Créer un modèle d'objet"
    usecase "Gérer un modèle d'objet"

    usecase "Modifier les caractéristiques du modèle d'objet"

    usecase "Ajouter les modèles d'emballages possibles"
}

"Administateur" -- "Créer un modèle d'objet"
"Administateur" -- "Gérer un modèle d'objet"

"Créer un modèle d'objet" --> "Gérer un modèle d'objet" : <<include>>

"Gérer un modèle d'objet" <-- "Modifier les caractéristiques du modèle d'objet" : <<extend>>
"Gérer un modèle d'objet" <-- "Ajouter les modèles d'emballages possibles" : <<extend>>

'note "L'administrateur peut modifier : le poids, le prix, la description..." as N1
'N1 .. "Modifier les caractéristiques du modèle d'objet"

title Diagramme de cas d'utilisation de la gestion des modèles d'objets dans le package Administateur
@enduml