@startuml Gestion administrative d'un emballage

actor "Administateur" 

package "Application interne DigiCheese" {
    usecase "Créer un emballage"
    usecase "Gérer un emballage"

    usecase "Modifier les caractéristiques de l'emballage"

    usecase "Ajouter les types d'objets possibles"
}

"Administateur" -- "Créer un emballage"
"Administateur" -- "Gérer un emballage"

"Créer un emballage" --> "Gérer un emballage" : <<include>>

"Gérer un emballage" <-- "Modifier les caractéristiques de l'emballage" : <<extend>>
"Gérer un emballage" <-- "Ajouter les types d'objets possibles" : <<extend>>

note "L'administrateur peut modifier : le poids, le prix, la description..." as N1
N1 .. "Modifier les caractéristiques de l'emballage"

title Diagramme de cas d'utilisation de la gestion des emballages dans le package Administateur
@enduml