@startuml Cas d'utilisation de la gestion de compte client côté administration
skinparam linetype ortho

actor "Opérateur colis" 
actor "Administateur" 

package "Application interne DigiCheese" {
    usecase "Créer un compte client"
    usecase "Gérer un compte client"
    usecase "Ajouter un solde"
    usecase "Modifier les information du compte" 

    usecase "Ajouter une commande au client" 
    usecase "Consulter les commandes en cours du client" 
    usecase "Consulter l'historique des commandes  du client" 

    usecase "Communiquer avec le ou les clients"
    'usecase Afficher_le_numéro_de_téléphone
    usecase "Envoyer un mail personalisé"
    usecase "Envoyer une newletters"

    usecase "Supprimer un compte client"

    usecase "Imprimer la liste des clients"
}

"Administateur"  -- "Supprimer un compte client"

"Opérateur colis"  <|-- "Administateur" 

"Opérateur colis"  -- "Créer un compte client"
"Opérateur colis"  -- "Gérer un compte client" 
"Opérateur colis"  -- "Imprimer la liste des clients"

"Créer un compte client" <-- "Gérer un compte client"  :<<include>>

"Gérer un compte client"  <-- "Ajouter un solde" : <<extend>>
"Gérer un compte client"  <-- "Ajouter une commande au client"  : <<extend>>
"Gérer un compte client"  <-- "Modifier les information du compte"  : <<extend>>

"Gérer un compte client"  <-- "Consulter les commandes en cours du client"  : <<extend>>
"Consulter les commandes en cours du client"  <-- "Consulter l'historique des commandes  du client"  : <<extend>>

"Opérateur colis"  -- "Communiquer avec le ou les clients"
'"Communiquer avec le ou les clients" <-- Afficher_le_numéro_de_téléphone : <<extend>>
"Communiquer avec le ou les clients" <-- "Envoyer un mail personalisé" : <<extend>>
"Communiquer avec le ou les clients" <-- "Envoyer une newletters" : <<extend>>

title Diagramme de cas d'utilisation de la gestion d'un compte client dans le package Administration de l'application


@enduml