@startuml Gestion administrative d'un emballage

actor "Administateur" 

package "Application interne DigiCheese" {
    usecase "Créer un modèle d'emballage"
    usecase "Gérer un modèle d'emballage"

    usecase "Modifier les caractéristiques du modèle d'emballage"

    usecase "Ajouter les modèles d'objets possibles"
}

"Administateur" -- "Créer un modèle d'emballage"
"Administateur" -- "Gérer un modèle d'emballage"

"Créer un modèle d'emballage" --> "Gérer un modèle d'emballage": <<include>>

"Gérer un modèle d'emballage" <-- "Modifier les caractéristiques du modèle d'emballage" : <<extend>>
"Gérer un modèle d'emballage" <-- "Ajouter les modèles d'objets possibles" : <<extend>>

'note "L'administrateur peut modifier : le poids, le prix, la description..." as N1
'N1 .. "Modifier les caractéristiques de l'emballage"

title Diagramme de cas d'utilisation de la gestion des modèles d'emballages dans le package Administateur
@enduml