@startuml Cas d'utilisation de la gestion de commande côté colis
'left to right direction
skinparam linetype polyline

actor "Opérateur colis"
actor "Administrateur"

package "Application interne DigiCheese"  {
    usecase "Accèder au compte client" 

    usecase "Créer une commande" 
    usecase "Gérer une commande" 

    usecase "Choissir les objets" 
    usecase "Choissir les emballages" 
    usecase "Choissir le tarif postal"

    'usecase Calcul_des_frais_de_ports
    usecase "Valider les frais de ports" 

    usecase "Ajouter un numéro de suivi" 

    usecase "Imprimer une commande" 
}

"Administrateur" --|> "Opérateur colis"

"Opérateur colis" -- "Créer une commande" 
"Opérateur colis" -- "Gérer une commande" 
"Opérateur colis" -- "Imprimer une commande" 

"Créer une commande"  --> "Accèder au compte client"  : <<include>>
"Créer une commande"  --> "Choissir les objets"  : <<include>>
"Choissir les objets"  --> "Choissir les emballages"  : <<include>>
"Choissir les emballages"  --> "Choissir le tarif postal" : <<include>>

"Créer une commande"  <-- "Gérer une commande"  : <<extend>>

"Gérer une commande"  <-- "Valider les frais de ports"  : <<extend>>
"Gérer une commande"  <-- "Ajouter un numéro de suivi"  : <<extend>>

'note "Ici le calcul des frais de ports fait références calcul du poids de l'emballage et des produits choisis\nPermet ensuite de le comparer au solde envoyer par le client pour vérifier que tout corresponds" as N1
note "La validation du conditionnement corresponds à la validation\ndes frais de ports de la commande par rapport au solde verser par le client" as N2

'N1 .. Calcul_des_frais_de_ports
N2 .. "Valider les frais de ports" 

title Diagramme de cas d'utilisation de la gestion d'une commande dans la partie Colis de l'application
@enduml