@startuml Classe model

class CompteClient {
    idClient : int
    nom : string
    prenom : string
    genre : string
    'adressePostal : string
    'codePostal : int
    'ville : string
    telephone : string
    adresseMail : string
    newsletters : boolean
    {field} solde : decimal(5,2)
}

class Commande {
    idCommande : int
    quantiteDObjets : int
    numeroDeSuivie : int
    {field} prix : decimal (5,2)
    {field} poids : decimal (5,2)
}

class Objet {
    idObjet : int
    nom : string
    description : string
    disponible : boolean
    {field} prix : decimal (5,2)
    {field} poids : decimal (5,2)
}

class Emballage {
    idEmballage : int
    nom : string
    {field} prix : decimal (5,2)
    {field} poids : decimal (5,2)
}

class Enseigne {
    idEnseigne : int
    nom : string
    'ville : string
    'codePostal : int
}

class TarifsPostaux {
    poidsMaximum : int
    {field} prix : decimal (5,2)
}

class AdressePostal {
    idAdressePostal : int
    adressePostal : string
    ville : string
    codePostal : int
}

enum Etat {
    PREPARATION
    ATTENTE DE VALIDATION DES FRAIS DE PORTS
    FRAIS DE PORTS VALIDES
    EXPEDIER
    TERMINER
    ANNULEE
    ERREUR
}


'class Conditionnement {}

'diamond dia

class Operateur {
    idOperateur : int
    nom : string
    motDePasse : string
}

class OperateurColis {

}

class OperateurStock {

}

class Administrateur {

}

CompteClient "1"-- "0..*" Commande : possède
Commande "1" -- "1..*" Objet : possède
Emballage "1" -- "1..*" Objet : contenir

CompteClient "1" -- "1..*" AdressePostal : possède
Commande "1..*" -- "1" AdressePostal : possède
Enseigne "1..*" -- "1"AdressePostal : possède

note "Avoir une classe adresse à part permettra de faire des statistiques\n sur les positions géographique plus simplement" as N1

N1 .. AdressePostal

'Emballage -- dia
'Objet -- dia
'Commande -- dia
'TarifsPostaux -- dia
'dia .. Conditionnement

'note "Suggestion pour calculer et montrer les liens pour le conditionnement" as N2
'N2 .. Conditionnement

Operateur <|-- OperateurColis
Operateur <|-- OperateurStock
OperateurStock <|-- Administrateur
OperateurColis <|-- Administrateur

Commande "0..1" -- "1"Etat :état

TarifsPostaux "1" -- "1..*" Commande : possède

Emballage"1..*" -- "1..*"Commande : contient

@enduml